baseURL: "https://techies-cdv.github.io/"
languageCode: "en-us"
title: "Techies"
theme: "PaperMod"

enableRobotsTxt: true

minify:
  disableXML: true
  minifyOutput: true

markup:
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: false
    style: github-dark

params:
  # Internal
  assets:
    disableHLJS: true
  # SEO related
  title: Techies
  description: "A technology club from Poznan, Poland!"
  keywords:
    ["Blog", "Technology Club", "Poznan", "Poland", "Software", "Design"]
  author: "Atakan Zengin"
  # landing page home mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to the club!
  socialIcons:
    - name: instagram
      url: "https://www.instagram.com/techies_cdv/"
    - name: github
      url: "https://github.com/techies-cdv"

  # post related
  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  editPost:
    URL: "https://github.com/techies-cdv/techies-cdv.github.io/blob/main/content/"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35
