baseURL: "http://example.org/"
languageCode: "en-us"
title: "Techies"
theme: "PaperMod"

enableRobotsTxt: true

minify:
  disableXML: true
  minifyOutput: true

params:
  # SEO related
  title: Techies
  description: "A technology club from Poznan, Poland!"
  keywords:
    ["Blog", "Technology Club", "Poznan", "Poland", "Software", "Design"]
  author: "Atakan Zengin"
  # landing page home mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to the club!
  socialIcons:
    - name: instagram
      url: "https://instagram.com/"
    - name: github
      url: "https://github.com/"

  # post related
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  editPost:
    URL: "https://github.com/atakanzen/techies/blob/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35
